// Readable wording for audit_logs actions shown in the dashboard.
const phrases: Record<string, string> = {
  "talent.created": "created a talent record",
  "talent.edited": "edited talent details",
  "talent.published": "published a talent to the website",
  "talent.unpublished": "removed a talent from the website",
  "talent.archived": "archived a talent",
  "talent.publication_changed": "changed a talent's publication status",
  "board.assigned": "added a talent to a board",
  "board.removed": "removed a talent from a board",
  "board.created": "created a board",
  "board.updated": "updated a board",
  "board.deleted": "deleted a board",
  "media.uploaded": "uploaded an image",
  "media.published": "made an image public",
  "media.unpublished": "made an image private",
  "media.archived": "archived an image",
  "media.edited": "edited image details",
  "media.primary_set": "set a primary image",
  "video.added": "added a video",
  "video.published": "made a video public",
  "video.unpublished": "made a video private",
  "video.archived": "archived a video",
  "sensitive.viewed": "viewed restricted records",
  "banking.revealed": "revealed banking details",
  "document.accessed": "downloaded a private document",
  "agency_member.insert": "approved a team member",
  "agency_member.update": "changed team access",
  "agency_member.delete": "removed a team member",
  "auth.login": "signed in",
  "auth.login_unapproved": "was refused sign-in (not on the team list)",
  "application.received": "received a Join Us application",
  "application.status_changed": "changed an application's status",
  "application.converted": "converted an application into talent",
  "application.purged": "purged old applications",
  "cms.page_published": "published a website page",
  "cms.page_unpublished": "took a website page offline",
  "cms.page_archived": "archived a website page",
  "cms.revision_restored": "restored an earlier version of a website page",
  "cms.settings_updated": "updated website settings",
  "booking.created": "created a booking",
  "booking.status_changed": "changed a booking's status",
  "booking.rescheduled": "rescheduled a booking",
  "booking.deleted": "deleted a booking",
  "booking.financials_changed": "updated booking fees",
  "finance.exported": "exported finance data",
  "package.created": "created a client package",
  "package.shared": "shared a client package link",
  "package.revoked": "revoked a client package link",
  "compcard.generated": "generated a comp card",
  "talent.exported": "exported the roster",
  "talent.exported_private": "exported the roster with private details",
};

export function describeAction(action: string) {
  if (phrases[action]) return phrases[action];
  const [subject, verb] = action.split(".");
  const noun = (subject ?? action).replaceAll("_", " ").replaceAll("-", " ");
  const past = { added: "added", updated: "updated", removed: "removed", saved: "saved", insert: "added", update: "updated", created: "created", deleted: "deleted" }[verb ?? ""];
  return past ? `${past} ${noun}` : action.replaceAll("_", " ").replace(".", " — ");
}
